name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update Git
        run: sudo apt-get update && sudo apt-get upgrade -y git
      - name: Set Git identity
        run: |
          git config --global user.name "zhengzy"
          git config --global user.email "2584007592@qq.com"
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies 
        run: npm install

      - name: Build VuePress site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.WW }}
          publish_dir: ./docs/.vuepress/dist
          publish_branch: gh-pages
