name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 触发条件可以根据你的需求进行调整

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          npm install
          npm run build
          cp -R docs/.vuepress/dist/* ../gh-pages/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SN }}
          publish_dir: ../gh-pages
