name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: zViewDocs-deploy
      uses: zzy-web/zViewDocs@main
      env:
        ACCESS_TOKEN: ${{ secrets.SN}}
        TARGET_REPO: zzy-web/zViewDocs
        TARGET_BRANCH: main
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/.vuepress/dist